import { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "特選 煎茶 [山霧]",
        price: 1200,
        description: "朝霧に包まれた山間部の茶畑で育った、爽やかな香りと深い味わいが特徴の煎茶です。",
        category: "sencha",
        tags: ["新茶", "爽やか"],
        taste_profile: { sweetness: 3, bitterness: 4, umami: 4, fragrance: 5 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    },
    {
        id: "2",
        name: "玉露 [朝露]",
        price: 2500,
        description: "直射日光を遮って育てた茶葉は、濃厚な甘みと旨みを凝縮しています。特別な一杯に。",
        category: "gyokuro",
        tags: ["限定", "濃厚"],
        taste_profile: { sweetness: 5, bitterness: 1, umami: 5, fragrance: 4 },
        images: ["/images/product_sencha.png"], // Reusing image for mock
        stock_status: "in_stock",
    },
    {
        id: "3",
        name: "上級 抹茶 [初音]",
        price: 1800,
        description: "石臼で丁寧に挽いた抹茶。点てて飲むのはもちろん、お菓子作りにも最適です。",
        category: "matcha",
        tags: ["定番", "点てる"],
        taste_profile: { sweetness: 2, bitterness: 2, umami: 4, fragrance: 5 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    },
    {
        id: "4",
        name: "常滑焼 急須",
        price: 4500,
        description: "職人が一つ一つ手作りした、お茶の味をまろやかにする常滑焼の急須。",
        category: "tool",
        tags: ["伝統工芸"],
        taste_profile: { sweetness: 0, bitterness: 0, umami: 0, fragrance: 0 }, // Not applicable but keeping schema
        images: ["/images/product_sencha.png"],
        stock_status: "limited",
    },
    {
        id: "5",
        name: "深蒸し煎茶 [緑雲]",
        price: 900,
        description: "通常の2倍の時間をかけて蒸した、濃い緑色とまろやかなコクが特徴。",
        category: "sencha",
        tags: ["深蒸し", "まろやか"],
        taste_profile: { sweetness: 4, bitterness: 2, umami: 3, fragrance: 3 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    },
    {
        id: "6",
        name: "茎茶 [かりがね]",
        price: 800,
        description: "玉露や高級煎茶の茎を集めた、独特の清涼感と甘みがあるお茶。",
        category: "sencha",
        tags: ["通好み", "さっぱり"],
        taste_profile: { sweetness: 3, bitterness: 3, umami: 3, fragrance: 4 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    },
    {
        id: "7",
        name: "ほうじ茶 [赤煉]",
        price: 600,
        description: "強火で焙煎した香ばしい香り。カフェイン少なめで夜にもおすすめ。",
        category: "sencha", // Hojicha category logic not separated strictly in mock but okay
        tags: ["香ばしい", "低カフェイン"],
        taste_profile: { sweetness: 3, bitterness: 1, umami: 2, fragrance: 5 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    },
    {
        id: "8",
        name: "抹茶入り玄米茶",
        price: 700,
        description: "香ばしい玄米と鮮やかな抹茶のハーモニー。",
        category: "sencha",
        tags: ["香ばしい", "鮮やか"],
        taste_profile: { sweetness: 3, bitterness: 2, umami: 3, fragrance: 4 },
        images: ["/images/product_sencha.png"],
        stock_status: "in_stock",
    }
];
